export enum PROJECT_SETUP_VIEWS {
  FETCH_WEBSITE_FORM = "FETCH_WEBSITE_FORM",
  PRE_PROJECT_DATA_FORM = "PRE_PROJECT_DATA_FORM",
  PROJECT_DATA_FROM = "PROJECT_DATA_FROM",
  ADD_SERVICES_FORM = "ADD_SERVICES_FORM",
  WEB_INFO_FORM = "WEB_INFO_FORM",
}
